### ISSUE TITLE
Error while creating accounts

### ISSUE THREAD

**Issue by raviloga** [engle2192/PoGoMap-GUI#44]
How do I fix this? I don't have 2captcha key. Is that the issue?

Traceback (most recent call last):
  File "c:\python27\scripts\pikaptcha-script.py", line 9, in <module>
    load_entry_point('Pikaptcha==0.1', 'console_scripts', 'pikaptcha')()
  File "c:\python27\lib\site-packages\pkg_resources__init__.py", line 542, in l
oad_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources__init__.py", line 2569, in
load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources__init__.py", line 2229, in
load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources__init__.py", line 2235, in
resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "c:\python27\lib\site-packages\pikaptcha\console.py", line 6, in <module>

```
from pikaptcha.tos import *
```

  File "c:\python27\lib\site-packages\pikaptcha\tos.py", line 3, in <module>
    from pgoapi import PGoApi
  File "c:\python27\lib\site-packages\pgoapi__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "c:\python27\lib\site-packages\pgoapi\pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "c:\python27\lib\site-packages\pgoapi\rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff,
Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash
, f2i
  File "c:\python27\lib\site-packages\pgoapi\utilities.py", line 30, in <module>

```
import xxhash
```

ImportError: DLL load failed: %1 is not a valid Win32 application.
You cannot call a method on a null-valued expression.
At C:\Users\username\Desktop\PoGoMap-GUI\PokemonGo-Map\usernamescsv.ps1:10 c
har:34
-     $usernames += ($csvname.split <<<< (",") | Select -index 1) + ":" + ($csv
  name.split(",") | Select -index 2) + ","
  - CategoryInfo          : InvalidOperation: (split:String) [], RuntimeExce
    ption
  - FullyQualifiedErrorId : InvokeMethodOnNull

Traceback (most recent call last):
  File "banned.py", line 6, in <module>
    from pgoapi import PGoApi
  File "c:\python27\lib\site-packages\pgoapi__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "c:\python27\lib\site-packages\pgoapi\pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "c:\python27\lib\site-packages\pgoapi\rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff,
Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash
, f2i
  File "c:\python27\lib\site-packages\pgoapi\utilities.py", line 30, in <module>

```
import xxhash
```

ImportError: DLL load failed: %1 is not a valid Win32 application.
You cannot call a method on a null-valued expression.
At C:\Users\username\Desktop\PoGoMap-GUI\PokemonGo-Map\usernamescsv.ps1:10 c
har:34
-     $usernames += ($csvname.split <<<< (",") | Select -index 1) + ":" + ($csv
  name.split(",") | Select -index 2) + ","
  - CategoryInfo          : InvalidOperation: (split:String) [], RuntimeExce
    ption
  - FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by Go2Engle** [comment]
Please checkout issue #28 and run through the steps there.
